defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  frontend:
    sso_name: "CASino"
    footer_text: "Powered by <a href=\"http://rbcas.com/\">CASino</a>"

development:
  <<: *defaults
  authenticators:
    static:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          testuser@example.com:
            password: "foobar123"
    meurio_accounts:
      authenticator: "ActiveRecord"
      options:
        connection:
          adapter: "postgresql"
          host: "localhost"
          # username: "nicolasiensen"
          database: "meurio_accounts_development"
        table: "users"
        username_column: "email"
        password_column: "encrypted_password"

test:
  <<: *defaults
  authenticators:
    static:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          testuser:
            password: "foobar123"

production: &production
  <<: *defaults
  authenticators:
    meurio_accounts:
      authenticator: "ActiveRecord"
      options:
        connection:
          adapter: "postgresql"
          host: <%= ENV["DB_HOST"] %>
          username: <%= ENV["DB_USER"] %>
          database: <%= ENV["DB_NAME"] %>
          password: <%= ENV["DB_PASSWORD"] %>
        table: "users"
        username_column: "email"
        password_column: "encrypted_password"

staging:
  <<: *production
